### ISSUE TITLE
Try to remember where I left off

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/tinycobol#1]
This currently doesn't build, and I can't remember any more where I was in the fixing process for it, either.

**Comment by cooljeanius** [comment]
from the looks of it, I hadn't even gotten out of the configury-editing phase yet...

**Comment by cooljeanius** [comment]
ok, I think I found the spot in `configure.ac` that I was at; leaving this open until I've gotten all the way through...

**Comment by cooljeanius** [comment]
so as of bc2013e I'm caught up with the edits I'd started from where I'd left off... the build is still broken, though, but that's a separate issue...

**Comment by GitMensch** [comment]
Just out of interest: Is there any specific you're interested in here (given the in-production-used GnuCOBOL [which started in parts on TinyCOBOL roots, even if nearly everything was rewritten] and the shiny new GCC 15.1 gcobol)?

**Comment by cooljeanius** [comment]
> Just out of interest: Is there any specific you're interested in here (given the in-production-used GnuCOBOL [which started in parts on TinyCOBOL roots, even if nearly everything was rewritten] and the shiny new GCC 15.1 gcobol)?

I forget! It's been over 12 years since I initially imported the tarball from SourceForge!
